"""Pydantic models for agent output schemas.

Each agent produces a typed output that flows through the graph state.
"""

from __future__ import annotations

from enum import StrEnum

from datetime import date, datetime, timezone
from typing import Any

from pydantic import BaseModel, Field


class RiskLevel(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class HealthStatus(StrEnum):
    """Overall health status for daily reports."""

    HEALTHY = "healthy"
    MONITOR = "monitor"
    CONCERN = "concern"


class TrendDirection(StrEnum):
    """Trend direction compared to baseline."""

    IMPROVING = "improving"
    STABLE = "stable"
    DECLINING = "declining"


class SourceStatusCode(StrEnum):
    OK = "ok"             # Source worked as intended
    DEGRADED = "degraded" # Partial success (e.g., some note details failed)
    FALLBACK = "fallback" # Source failed, alternative used
    SKIPPED = "skipped"   # Source not available/configured


class SourceStatus(BaseModel):
    """Status of a single data source used during advice generation."""

    source: str = Field(description="e.g. 'Medical Knowledge Base'")
    status: SourceStatusCode
    message: str = Field(description="User-facing explanation of what happened")


class Citation(BaseModel):
    """A single source citation attached to advice."""

    source_type: str = Field(description="e.g. 'data_analysis', 'book', 'medical', 'xhs_post'")
    reference: str = Field(description="e.g. 'AAP Immunization Guide, p.42'")
    detail: str | None = None


class TrendAnomaly(BaseModel):
    """A single anomaly detected in physiology data."""

    date: str
    metric: str
    value: float
    baseline: float
    deviation_pct: float = Field(description="Percentage deviation from baseline")
    description: str


class TrendAnalysis(BaseModel):
    """Output of the Data Scientist agent."""

    summary: str
    data_summary: str = Field(
        default="",
        description="Human-readable summary of raw daily aggregates and context events",
    )
    anomalies: list[TrendAnomaly] = Field(default_factory=list)
    correlations: list[str] = Field(
        default_factory=list,
        description="Context events correlated with anomalies",
    )
    citations: list[Citation] = Field(default_factory=list)


class MedicalInsight(BaseModel):
    """Output of the Medical Expert agent."""

    summary: str
    risk_level: RiskLevel = RiskLevel.LOW
    recommendations: list[str] = Field(default_factory=list)
    citations: list[Citation] = Field(default_factory=list)
    kb_available: bool | None = Field(
        default=None,
        description="True=RAG succeeded, False=LLM-only/KB failed, None=unknown",
    )
    raw_kb_snippets: list[str] = Field(
        default_factory=list,
        description="Raw document excerpts for degraded-mode display",
    )


class SocialInsight(BaseModel):
    """Output of the Social Researcher agent."""

    summary: str
    consensus_points: list[str] = Field(default_factory=list)
    sample_size: int = Field(default=0, description="Number of posts/discussions analyzed")
    citations: list[Citation] = Field(default_factory=list)
    agrees_with_medical: bool | None = Field(
        default=None,
        description="True=agrees, False=contradicts, None=unknown",
    )
    raw_social_posts: list[str] = Field(
        default_factory=list,
        description="Raw post snippets for degraded-mode display",
    )


class CritiqueResult(BaseModel):
    """Output of the Critique node (reflection loop)."""

    approved: bool
    confidence_score: float = Field(ge=0.0, le=1.0)
    issues: list[str] = Field(default_factory=list)
    suggestions: list[str] = Field(default_factory=list)


class ParentingAdvice(BaseModel):
    """Final synthesized output delivered to the parent."""

    question: str
    summary: str
    key_points: list[str] = Field(default_factory=list)
    action_items: list[str] = Field(default_factory=list)
    risk_level: RiskLevel = RiskLevel.LOW
    confidence_score: float = Field(ge=0.0, le=1.0)
    citations: list[Citation] = Field(default_factory=list)
    sources_used: list[SourceStatus] = Field(default_factory=list)
    is_degraded: bool = False
    raw_sources: list[str] = Field(
        default_factory=list,
        description="Raw source snippets shown when synthesis is degraded",
    )
    disclaimer: str = (
        "This is AI-generated guidance and not a substitute for professional medical advice. "
        "Always consult your pediatrician for health concerns."
    )


class DailyReport(BaseModel):
    """Automated daily health report for a baby.

    Generated by the push-model daily report pipeline, which analyzes
    the day's PhysiologyLog and ContextEvent data against a 7-day baseline.
    """

    baby_id: str
    baby_name: str
    report_date: date

    # Health assessment
    health_status: HealthStatus = HealthStatus.HEALTHY
    confidence_score: float = Field(ge=0.0, le=1.0, default=0.8)
    trend_direction: TrendDirection = TrendDirection.STABLE

    # Report content
    summary: str = Field(description="2-3 sentence health overview for the day")
    observations: list[str] = Field(
        default_factory=list,
        description="Key observations from today's data",
    )
    action_items: list[str] = Field(
        default_factory=list,
        description="Actionable tips for parents based on today's patterns",
    )
    warnings: list[str] = Field(
        default_factory=list,
        description="Flags that may warrant pediatrician attention",
    )

    # Citations
    citations: list[Citation] = Field(default_factory=list)

    # Data context (for transparency and debugging)
    data_snapshot: dict[str, Any] = Field(
        default_factory=dict,
        description="Today's aggregated data (feeding_ml, sleep_min, diaper_count)",
    )
    baseline_snapshot: dict[str, Any] = Field(
        default_factory=dict,
        description="7-day rolling baseline for comparison",
    )

    # Metadata
    generated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    disclaimer: str = (
        "This daily report is AI-generated based on logged data. "
        "It is not a substitute for professional medical advice."
    )
